apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
