# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: dXNlcm5hbWU=     # base64 encoded value of "username"
  password: UGFzc3cwcmQxMjM=     # base64 encoded value of "password"
